apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}
  namespace: default
  labels:
    app: ${PROJECT_NAME}
spec:
  selector:
    app: ${PROJECT_NAME}
  type: NodePort
  ports:
    - name: app
      port: 80
      targetPort: 9000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  labels:
    app: ${PROJECT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
    spec:
      containers:
        - name: ${PROJECT_NAME}
          image: gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}:0.1.${CIRCLE_BUILD_NUM}
